name: ffmpeg_kit_flutter
description: FFmpeg Kit for Flutter. Supports Android, iOS and macOS platforms.
repository: https://github.com/arthenica/ffmpeg-kit
issue_tracker: https://github.com/arthenica/ffmpeg-kit/issues
homepage: https://github.com/arthenica/ffmpeg-kit
version: 6.0.3

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=3.19.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.ffmpegkit.flutter
        pluginClass: FFmpegKitFlutterPlugin
      ios:
        pluginClass: FFmpegKitFlutterPlugin
      macos:
        pluginClass: FFmpegKitFlutterPlugin

dependencies:
  ffmpeg_kit_flutter_platform_interface:
    git:
      url: https://github.com/Carapacik/ffmpeg-kit
      path: flutter/flutter_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  carapacik_lints: ^1.11.1
